CREATE DATABASE IF NOT EXISTS trafficone;

CREATE TABLE IF NOT EXISTS trafficone.clicks
(
    event_time DateTime,
    event_id String DEFAULT '',
    click_id String,
    subid String DEFAULT '',
    campaign_id UInt64,
    campaign_slug String,
    flow_id UInt64,
    stream_id UInt64,
    destination_id UInt64,
    ip String,
    user_agent String,
    referrer String,
    destination_url String,
    source String DEFAULT '',
    country String DEFAULT '',
    region String DEFAULT '',
    city String DEFAULT '',
    os String DEFAULT '',
    os_version String DEFAULT '',
    browser String DEFAULT '',
    browser_version String DEFAULT '',
    connection_type String DEFAULT '',
    device_type String DEFAULT '',
    device_model String DEFAULT '',
    bot UInt8 DEFAULT 0,
    unique_campaign UInt8 DEFAULT 1,
    unique_flow UInt8 DEFAULT 1,
    unique_global UInt8 DEFAULT 1,
    event_type String DEFAULT 'click',
    site String DEFAULT '',
    x_requested_with String DEFAULT '',
    search_engine String DEFAULT '',
    keyword String DEFAULT '',
    visitor_code String DEFAULT '',
    ad_campaign_id String DEFAULT '',
    external_id String DEFAULT '',
    creative_id String DEFAULT '',
    cost Float64 DEFAULT 0,
    domain String DEFAULT '',
    language String DEFAULT '',
    ip_1_2_mask String DEFAULT '',
    ip_1_2_3_mask String DEFAULT '',
    empty_referrer UInt8 DEFAULT 0,
    using_proxy UInt8 DEFAULT 0,
    landing_clicked UInt8 DEFAULT 0,
    destination_type String DEFAULT '',
    sub_id_1 String DEFAULT '',
    sub_id_2 String DEFAULT '',
    sub_id_3 String DEFAULT '',
    sub_id_4 String DEFAULT '',
    sub_id_5 String DEFAULT '',
    sub_id_6 String DEFAULT '',
    sub_id_7 String DEFAULT '',
    sub_id_8 String DEFAULT '',
    sub_id_9 String DEFAULT '',
    sub_id_10 String DEFAULT '',
    sub_id_11 String DEFAULT '',
    sub_id_12 String DEFAULT '',
    sub_id_13 String DEFAULT '',
    sub_id_14 String DEFAULT '',
    sub_id_15 String DEFAULT '',
    sub_id_16 String DEFAULT '',
    sub_id_17 String DEFAULT '',
    sub_id_18 String DEFAULT '',
    sub_id_19 String DEFAULT '',
    sub_id_20 String DEFAULT '',
    sub_id_21 String DEFAULT '',
    sub_id_22 String DEFAULT '',
    sub_id_23 String DEFAULT '',
    sub_id_24 String DEFAULT '',
    sub_id_25 String DEFAULT '',
    sub_id_26 String DEFAULT '',
    sub_id_27 String DEFAULT '',
    sub_id_28 String DEFAULT '',
    sub_id_29 String DEFAULT '',
    sub_id_30 String DEFAULT ''
)
ENGINE = MergeTree
ORDER BY (campaign_id, event_time, click_id);

CREATE TABLE IF NOT EXISTS trafficone.conversions
(
    event_time DateTime,
    click_id String,
    transaction_id String,
    goal String,
    payout Float64,
    currency String,
    status String
)
ENGINE = MergeTree
ORDER BY (event_time, click_id, goal);
